services:
  - type: web
    name: rectificadora-backend
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_PORT
        value: "10000"
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: CSRF_COOKIE_SECURE
        value: "true"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
