package com.rectificadora.gestion.domain;

public final class Enums {
  private Enums() {
  }

  public enum Role {
    ADMIN, OPERADOR, EMPLEADO_TALLER
  }

  public enum Permission {
    ORDENES_GESTIONAR, CLIENTES_DATOS_BASICOS, CLIENTES_VER_HISTORIAL, CATALOGO_GESTIONAR,
    PAGOS_REGISTRAR, FINANZAS_VER, ESTADISTICAS_VER, AUDITORIA_VER, USUARIOS_GESTIONAR,
    RESPALDOS_GESTIONAR, TAREAS_TALLER
  }

  public enum OrderStatus {
    RECEPCION, EN_PROCESO, FINALIZADO, ENTREGADO, CANCELADO
  }

  public enum TaskCategory {
    BLOCK, REPUESTO, TAPA, CIGUENAL, OTRO
  }

  public enum PaymentMethod {
    EFECTIVO, TRANSFERENCIA, TARJETA, CHEQUE, OTRO
  }

  public enum EstadoTareaTaller {
    DISPONIBLE, ASIGNADA, ACEPTADA, EN_PROCESO, PENDIENTE, FINALIZADA
  }

  public enum AccionTareaTaller {
    CREADA, ASIGNADA, REASIGNADA, LIBERADA, ACEPTADA, INICIADA, PAUSADA, RETOMADA, FINALIZADA, REABIERTA
  }
}
