package com.rectificadora.gestion.web;
import com.rectificadora.gestion.domain.*; import com.rectificadora.gestion.repository.*; import com.rectificadora.gestion.service.AuditService;
import jakarta.transaction.Transactional; import jakarta.validation.Valid; import jakarta.validation.constraints.*;
import org.springframework.http.HttpStatus; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/orders") public class WorkOrderController {
  private final WorkOrderRepository orders; private final ClientRepository clients; private final VehicleRepository vehicles; private final CatalogTaskRepository tasks; private final AuditService audit;
  WorkOrderController(WorkOrderRepository o,ClientRepository c,VehicleRepository v,CatalogTaskRepository t,AuditService a){orders=o;clients=c;vehicles=v;tasks=t;audit=a;}
  public record ItemInput(UUID taskId,@NotBlank String description,@NotNull Enums.TaskCategory category,@NotNull @PositiveOrZero BigDecimal unitPrice,@Min(1) int quantity){}
  public record OrderInput(@NotNull UUID clientId,UUID vehicleId,LocalDate promisedDate,@NotNull Enums.OrderStatus status,Integer cylinders,String finalMeasure,String receptionDescription,String notes,List<ItemInput> items){}
  public record PaymentInput(@NotNull @Positive BigDecimal amount,@NotNull Enums.PaymentMethod method,String details){}
  @GetMapping @Transactional public List<ApiDtos.OrderView> list(@RequestParam(defaultValue="") String q){return (q.isBlank()?orders.findAll().stream().sorted(Comparator.comparing((WorkOrder w)->w.createdAt).reversed()).toList():orders.search(q)).stream().map(ApiDtos::order).toList();}
  @GetMapping("/{id}") @Transactional public ApiDtos.OrderView get(@PathVariable UUID id){return ApiDtos.order(orders.findById(id).orElseThrow());}
  @PostMapping @ResponseStatus(HttpStatus.CREATED) @Transactional public ApiDtos.OrderView create(@Valid @RequestBody OrderInput in){var w=apply(new WorkOrder(),in);w.orderNumber=nextNumber();w=orders.save(w);audit.record("CREATE","ORDER",w.id,w.orderNumber);return ApiDtos.order(w);}
  @PutMapping("/{id}") @PreAuthorize("hasRole('ADMIN')") @Transactional public ApiDtos.OrderView update(@PathVariable UUID id,@Valid @RequestBody OrderInput in){var w=orders.findById(id).orElseThrow();w.items.clear();apply(w,in);w=orders.save(w);audit.record("UPDATE","ORDER",w.id,w.orderNumber);return ApiDtos.order(w);}
  @PatchMapping("/{id}/status") @Transactional public ApiDtos.OrderView status(@PathVariable UUID id,@RequestParam Enums.OrderStatus value){var w=orders.findById(id).orElseThrow();w.status=value;w=orders.save(w);audit.record("STATUS","ORDER",w.id,w.orderNumber+" -> "+value);return ApiDtos.order(w);}
  @PostMapping("/{id}/payments") @PreAuthorize("hasRole('ADMIN')") @Transactional public ApiDtos.OrderView pay(@PathVariable UUID id,@Valid @RequestBody PaymentInput in,java.security.Principal principal){var w=orders.findById(id).orElseThrow();if(in.amount().compareTo(w.getBalance())>0)throw new IllegalArgumentException("El pago supera el saldo pendiente");var p=new Payment();p.workOrder=w;p.amount=in.amount();p.method=in.method();p.details=in.details();p.registeredBy=principal.getName();w.payments.add(p);w.paid=w.paid.add(p.amount);w=orders.save(w);audit.record("PAYMENT","ORDER",w.id,w.orderNumber+" $"+p.amount);return ApiDtos.order(w);}
  private WorkOrder apply(WorkOrder w,OrderInput in){w.client=clients.findById(in.clientId()).orElseThrow();w.vehicle=in.vehicleId()==null?null:vehicles.findById(in.vehicleId()).orElseThrow();w.promisedDate=in.promisedDate();w.status=in.status();w.cylinders=in.cylinders();w.finalMeasure=in.finalMeasure();w.receptionDescription=in.receptionDescription();w.notes=in.notes();BigDecimal total=BigDecimal.ZERO;if(in.items()!=null)for(var i:in.items()){var x=new WorkOrderItem();x.workOrder=w;x.catalogTask=i.taskId()==null?null:tasks.findById(i.taskId()).orElse(null);x.description=i.description();x.category=i.category();x.unitPrice=i.unitPrice();x.quantity=i.quantity();w.items.add(x);total=total.add(i.unitPrice().multiply(BigDecimal.valueOf(i.quantity())));}w.total=total;return w;}
  private String nextNumber(){int year=Year.now().getValue();long seq=orders.nextOrderSequence();return "OT-"+year+"-"+String.format("%05d",seq);}
}
